name: Python CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy_lambda:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Package Lambda Function
        run:  |
          zip -r lambda-deployment.zip *

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      # Deploy to AWS Lambda using AWS CLI
      - name: Deploy to AWS Lambda
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'us-east-1'
        run: |
          aws lambda velo \
            --function-name YOUR_LAMBDA_FUNCTION_NAME \
            --zip-file fileb://lambda-deployment.zip



