name: Python CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy_lambda:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: 'us-east-1'

      - name: Package and Deploy to AWS Lambda
        run: |
          zip -r lambda-deployment.zip *
          aws lambda velo \
            --function-name YOUR_LAMBDA_FUNCTION_NAME \
            --zip-file fileb://lambda-deployment.zip



